### ISSUE TITLE
CI failure: Run Tests — TypeError: harness.triggerAgent is not a function

### ISSUE THREAD

**Issue by asselstine** [Action-Llama/action-llama#282]
## CI Failure Report

**Workflow:** CI  
**Branch:** main  
**Commit:** f4ad10da325d000e0b626673e4edc1876bc578b5  
**Run:** https://github.com/Action-Llama/action-llama/actions/runs/23412063722

## Failure Summary

The integration tests are failing because they're trying to call `harness.triggerAgent()` which doesn't exist. This was introduced in commit f4ad10d which removed automatic initial runs of scheduled agents and added manual triggers to tests.

### Run Tests

**Error output:**
```
TypeError: harness.triggerAgent is not a function
 ❯ packages/action-llama/test/integration/scheduler.test.ts:45:19
    43|
    44|    // Manually trigger the agent since there are no more automatic initial runs
    45|    await harness.triggerAgent("cron-agent");
       |                  ^
    46|
```

Multiple tests are affected:
- `scheduler.test.ts`: lines 45, 71, 72
- Various timeout errors in other integration tests (signals.test.ts, triggers.test.ts, webhooks.test.ts)

## Root Cause Analysis

The commit "Remove automatic initial runs of scheduled agents on startup (#275)" modified the test files to use `harness.triggerAgent()` to manually trigger agent runs, but this method was never implemented in the test harness (`packages/action-llama/test/integration/harness.ts`).

The `triggerAgent` functionality exists in the gateway control API at `POST /control/trigger/:name`, but it's not exposed through the test harness interface.

## Suggested Fix

Add a `triggerAgent` method to the IntegrationHarness class that calls the control API:

```diff
--- a/packages/action-llama/test/integration/harness.ts
+++ b/packages/action-llama/test/integration/harness.ts
@@ -263,6 +263,20 @@ export class IntegrationHarness {
     });
   }
 
+  /**
+   * Manually trigger an agent run via the control API.
+   */
+  async triggerAgent(agentName: string): Promise<void> {
+    const response = await this.controlAPI('POST', `/trigger/${agentName}`);
+    if (!response.ok) {
+      const error = await response.text();
+      throw new Error(`Failed to trigger agent ${agentName}: ${error}`);
+    }
+    const result = await response.json();
+    if (!result.success) {
+      throw new Error(`Failed to trigger agent ${agentName}: ${result.error || 'Unknown error'}`);
+    }
+  }
+
   /**
    * Wait for an agent to complete at least one run.
    * Polls the runner pool until the agent is no longer running.
```

## Additional Context

Recent commit f4ad10d made breaking changes to remove automatic initial runs, but the test infrastructure wasn't fully updated to support the new manual triggering requirement.

---
*This issue was automatically created by the gh-actions-responder agent.*

**Comment by asselstine** [comment]
PR created: https://github.com/Action-Llama/action-llama/pull/283
