### ISSUE TITLE
CI failure: CI — Missing triggerAgent method in test harness

### ISSUE THREAD

**Issue by asselstine** [Action-Llama/action-llama#288]
## CI Failure Report

**Workflow:** CI
**Branch:** main
**Commit:** 2da001f632d754e19f98b1fd3f5de58771392165
**Run:** https://github.com/Action-Llama/action-llama/actions/runs/23412456270

## Failure Summary

Multiple integration tests are failing because they call `harness.triggerAgent()` but this method does not exist in the test harness. This was introduced by commit f4ad10d which removed automatic initial runs of scheduled agents but failed to implement the manual trigger method used in the updated tests.

### Run Tests

**Error output:**
```
FAIL packages/action-llama/test/integration/scheduler.test.ts > integration: scheduler > starts scheduler, builds images, runs cron agent, gateway responds to health
TypeError: harness.triggerAgent is not a function
❯ packages/action-llama/test/integration/scheduler.test.ts:45:19
    44|     // Manually trigger the agent since there are no more automatic initial runs
    45|     await harness.triggerAgent("cron-agent");
       |                   ^
    46|
```

Additionally, many other tests are timing out with "Agent did not complete within 120000ms" errors, likely because agents are not being triggered properly.

## Root Cause Analysis

In commit f4ad10d ("Remove automatic initial runs of scheduled agents on startup"), the test files were updated to manually trigger agents using `await harness.triggerAgent("agent-name")`. However, this method was never implemented in the test harness class.

The gateway provides a REST endpoint `POST /control/trigger/<name>` for triggering agents manually, but the test harness doesn't expose this functionality.

## Suggested Fix

Add the missing `triggerAgent` method to the test harness. The implementation should:

1. Make an authenticated HTTP POST request to the gateway's trigger endpoint
2. Wait for the agent to be scheduled/started

Here's the suggested implementation for `packages/action-llama/test/integration/harness.ts`:

```diff
+  /**
+   * Manually trigger an agent run via the gateway API.
+   */
+  async triggerAgent(agentName: string): Promise<void> {
+    if (!this._scheduler) {
+      throw new Error("Harness not started — call start() first");
+    }
+
+    const gatewayPort = this._scheduler.gateway?.port;
+    if (!gatewayPort) {
+      throw new Error("Gateway not available");
+    }
+
+    // Read the gateway API key
+    const apiKeyPath = path.join(os.homedir(), ".action-llama/credentials/gateway_api_key/default/key");
+    let apiKey: string;
+    try {
+      apiKey = await fs.readFile(apiKeyPath, "utf-8");
+      apiKey = apiKey.trim();
+    } catch (err) {
+      throw new Error(`Failed to read gateway API key: ${err}`);
+    }
+
+    // Trigger the agent via gateway API
+    const response = await fetch(`http://localhost:${gatewayPort}/control/trigger/${agentName}`, {
+      method: "POST",
+      headers: {
+        "Authorization": `Bearer ${apiKey}`,
+        "Content-Type": "application/json"
+      }
+    });
+
+    if (!response.ok) {
+      throw new Error(`Failed to trigger agent ${agentName}: ${response.status} ${response.statusText}`);
+    }
+  }
```

## Additional Context

This issue affects 11 test files with 33 failing tests in total. All integration tests that rely on scheduled agents are broken. The commit that introduced this regression was merged on Sun Mar 22 13:42:01 2026.

---
*This issue was automatically created by the gh-actions-responder agent.*

**Comment by asselstine** [comment]
## Another CI failure occurred

**Workflow:** CI
**Branch:** main  
**Commit:** 4aa001bd46222e5e3fa4c0e9fcf7bb49338cb3c7
**Run:** https://github.com/Action-Llama/action-llama/actions/runs/23412466057
**Time:** 2026-03-22T21:27:12.729Z

The same error is still occurring - multiple integration tests failing due to missing `harness.triggerAgent()` method. This indicates the issue has not been resolved yet.

Failed tests include:
- scheduler.test.ts: Tests for scheduler functionality
- signals.test.ts: Tests for exit codes and signal handling  
- triggers.test.ts: Tests for agent-to-agent triggers
- webhooks.test.ts: Tests for webhook-triggered agents

All tests are failing with either:
- `TypeError: harness.triggerAgent is not a function`
- Timeout errors (`Agent "<name>" did not complete within 120000ms`)

This confirms the issue is still present and affecting the CI pipeline.
